# Generated by Django 3.2.5 on 2021-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=264),
        ),
    ]
