# Generated by Django 3.2.5 on 2021-08-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0005_auto_20210821_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='Business', on_delete=django.db.models.deletion.CASCADE, to='App_Blog.category'),
        ),
    ]
